language: node_js

branches:
  only:
    - gh-pages

env:
  global:
    - URL="https://w3c.github.io/webrtc-stats/W3CTRMANIFEST"
    - DECISION="https://lists.w3.org/Archives/Public/public-webrtc/2016Mar/0031.html"
    - secure: "VD097GRyqSACTjhUDkrPnZv80shH2Uh5g66cxXsO95hVA1ZrLUtbwS4aQshcQrcl28uVpsJ2E/OpeHHg1HbmNv9uVdsvbnEztGxu7wm6xUi0ZXK81uYqOZtvbbnipjZywe45wTjLYJOGiYgsN9yEN1arHXAPR9lmNInt0QIf10M="

script:
  - echo "ok"

after_success:
  - [[ $TRAVIS_PULL_REQUEST == 'false' ]] && curl "https://labs.w3.org/echidna/api/request" --data "url=$URL" --data "decision=$DECISION" --data "token=$TOKEN"
