language: python

dist: trusty

branches:
  only:
    - /.*/

python:
  - "2.7_with_system_site_packages"

sudo: false

addons:
  apt:
    packages:
      - libwww-perl
      - libcss-dom-perl
      - python-lxml
      - cmake
      - gcc-4.8
      - g++-4.8
  chrome: stable

cache:
  directories:
    - node_modules # NPM packages

before_install:
  - nvm install lts/*

install:
 - make travissetup

script:
 - make check

env:
  global:
    - URL="https://w3c.github.io/webrtc-stats/W3CTRMANIFEST"
    - DECISION="https://lists.w3.org/Archives/Public/public-webrtc/2016Mar/0031.html"
    - secure: "VD097GRyqSACTjhUDkrPnZv80shH2Uh5g66cxXsO95hVA1ZrLUtbwS4aQshcQrcl28uVpsJ2E/OpeHHg1HbmNv9uVdsvbnEztGxu7wm6xUi0ZXK81uYqOZtvbbnipjZywe45wTjLYJOGiYgsN9yEN1arHXAPR9lmNInt0QIf10M="

after_success:
  - test $TRAVIS_BRANCH = "master" -a $TRAVIS_PULL_REQUEST = false && curl "https://labs.w3.org/echidna/api/request" --data "url=$URL" --data "decision=$DECISION" --data "token=$TOKEN"
